#
# definition of dracula theme

# theme file stuff to work out
# - how to declare a "whatever your terminal chooses" color
#     - fzf uses -1 for this
#     - rich uses "default"

# information heirarchy
# 'styles'
# 'domains'
#    domain - ie fzf
#       - domain_type
#    element - ie label
#    value - ie '$ff79c6'
#
# - domain can be the name of a  and element could be the color
# - domain could be the name of an environment variable, and element could be the value

# styles defined here use the syntax of the python rich library
name = "dracula"

[styles]
# these are from https://draculatheme.com/contribute
# we don't use the background color here, we just leave it to the terminal
# background color
background =  "#282a36"
foreground =  "#f8f8f2"

# styles for text and the highlighted line
# these are the only things fzf supports background colors for
text = "#f8f8f2 on default"
current_line =  "#f8f8f2 on #44475a"

# other colors from the dracula palette
comment =  "#6272a4"
cyan =  "#8be9fd"
green =  "#50fa7b"
orange =  "#ffb86c"
pink =  "#ff79c6"
purple =  "#bd93f9"
red =  "#ff5555"
yellow =  "#f1fa8c"


[domain.fzf]
type = "fzf"

# attributes specific to fzf
varname = "FZF_DEFAULT_OPTS"

# command line options
# opt.border = "single" --> --border=single
# opt.no-sort = true --> --no-sort
# opt.no-sort = false does not add anything to the output
opt.border = "single"
opt.pointer = "•"
opt.info = "hidden"
opt.no-sort = true
opt.prompt = ">"

# visual styles for each element

# the fzf module uses the bw base scheme, with turns all colors off
# if you don't specify a color here, it will draw in your terminal
# default foreground color

# fzf only supports a few background colors, and they are notated
# separately from the foreground
# so we map the following:
#   text -> fg and bg
#   current_line -> fg+ and bg+
#   preview -> preview-fg and preview-bg
# background colors on all other styles are ignored
#

# these styles are special because they set
style.text = "text"
style.current_line = "current_line"

# no special parsing for these styles, just use the fzf color name
style.label = "green"
style.border = "orange"
style.prompt = "green"
style.pointer = "cyan"
style.query = "pink"


[domain.fdirs]
# uses fzf, if you want something different than the default fzf
# set the colors here
text = "foreground"
label = "green"
border = "orange"
prompt = "green"
indicator = "cyan"
match = "pink"
selected = "current_line"

[domain.bash-control-r]
# this uses fzf, if you want something differnet than the default fzf
# add colors here
text = "foreground"
label = "green"
border = "orange"
prompt = "green"
indicator = "cyan"
match = "pink"
selected = "current_line"
