#
# definition of dracula theme
version = 1

[meta]
name = "dracula"

[styles]
background =  "#282a36"
foreground =  "#f8f8f2"
current_line =  "#44475a"
comment =  "#6272a4"
cyan =  "#8be9fd"
green =  "#50fa7b"
orange =  "#ffb86c"
pink =  "#ff79c6"
purple =  "#bd93f9"
red =  "#ff5555"
yellow =  "#f1fa8c"

[scopes.fdirs]
text = "foreground"
label = "green"
border = "orange"
prompt = "green"
indicator = "cyan"
match = "pink"
selected = "current_line"

[scopes.bash-control-r]
text = "foreground"
label = "green"
border = "orange"
prompt = "green"
indicator = "cyan"
match = "pink"
selected = "current_line"
